/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,jsx}",
    "./components/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        cx: {
          base: "#0B1220",
          deep: "#0E1629",
          surface: "#131B2E",
          card: "#172033",
          cardHover: "#1C2740",
          border: "#1E293B",
          borderLight: "#2A3A52",
          accent: "#3B82F6",
          accentHover: "#2563EB",
          accentDim: "#1E40AF",
          accentGlow: "rgba(59,130,246,0.15)",
          alert: "#EF4444",
          alertGlow: "rgba(239,68,68,0.12)",
          violet: "#8B5CF6",
          violetGlow: "rgba(139,92,246,0.1)",
          text: "#F1F5F9",
          textSec: "#94A3B8",
          textDim: "#64748B",
          textGhost: "#475569",
        },
        risk: {
          low: "#10B981",
          lowGlow: "rgba(16,185,129,0.1)",
          med: "#F59E0B",
          medGlow: "rgba(245,158,11,0.1)",
          high: "#F97316",
          highGlow: "rgba(249,115,22,0.1)",
          crit: "#EF4444",
          critGlow: "rgba(239,68,68,0.1)",
        },
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "-apple-system", "sans-serif"],
        mono: ["JetBrains Mono", "Fira Code", "monospace"],
      },
      animation: {
        "fade-in": "fadeIn 0.6s ease-out forwards",
        "slide-up": "slideUp 0.6s ease-out forwards",
        "slide-right": "slideRight 0.5s ease-out forwards",
        "gauge": "gaugeDraw 1.8s ease-out forwards",
        "float-a": "floatA 7s ease-in-out infinite",
        "float-b": "floatB 9s ease-in-out 1.5s infinite",
        "glow-pulse": "glowPulse 2.5s ease-in-out infinite",
        "bar-grow": "barGrow 1s ease-out forwards",
        "shimmer": "shimmer 1.8s ease-in-out infinite",
      },
      keyframes: {
        fadeIn: { "0%": { opacity: 0 }, "100%": { opacity: 1 } },
        slideUp: { "0%": { opacity: 0, transform: "translateY(24px)" }, "100%": { opacity: 1, transform: "translateY(0)" } },
        slideRight: { "0%": { opacity: 0, transform: "translateX(-16px)" }, "100%": { opacity: 1, transform: "translateX(0)" } },
        gaugeDraw: { "0%": { strokeDashoffset: 264 } },
        floatA: { "0%,100%": { transform: "translateY(0) rotate(0deg)" }, "50%": { transform: "translateY(-18px) rotate(2deg)" } },
        floatB: { "0%,100%": { transform: "translateY(0) rotate(0deg)" }, "50%": { transform: "translateY(-14px) rotate(-1.5deg)" } },
        glowPulse: { "0%,100%": { boxShadow: "0 0 0 0 rgba(239,68,68,0.3)" }, "50%": { boxShadow: "0 0 0 10px rgba(239,68,68,0)" } },
        barGrow: { "0%": { width: "0%" } },
        shimmer: { "0%": { backgroundPosition: "-200% 0" }, "100%": { backgroundPosition: "200% 0" } },
      },
    },
  },
  plugins: [],
};