/**
 * simulations.js
 * Static data for the Scam Simulation Lab.
 * Each scenario contains steps, psychology, interventions, and prevention.
 */

const SIMULATIONS = [
  {
    id: "bank-kyc",
    title: "Bank KYC Fraud",
    short: "KYC Update",
    icon: "bank",
    description: "Impersonates a bank and threatens account closure unless KYC is updated via a malicious link.",
    steps: [
      {
        sender: "scammer",
        message: "Dear Customer, your SBI account has been temporarily suspended due to incomplete KYC verification.",
        riskScore: 20,
        tactics: ["Authority"],
        commentary: "Authority impersonation begins — the scammer establishes credibility by naming a real bank.",
      },
      {
        sender: "scammer",
        message: "Your account will be permanently blocked within 24 hours if KYC is not updated immediately.",
        riskScore: 45,
        tactics: ["Authority", "Fear"],
        commentary: "Fear is introduced — the threat of permanent account closure creates panic.",
      },
      {
        sender: "scammer",
        message: "Click here to update your KYC now: http://sbi-kyc-secure-update.co.in",
        riskScore: 75,
        tactics: ["Authority", "Fear", "Urgency"],
        commentary: "The malicious URL is presented. This is a typosquatted domain designed to look legitimate.",
      },
      {
        sender: "victim",
        message: "I clicked the link and entered my details...",
        riskScore: 90,
        tactics: ["Authority", "Fear", "Urgency"],
        commentary: "The victim has submitted credentials to a phishing page. Account compromise is now likely.",
      },
      {
        sender: "scammer",
        message: "Please share the OTP sent to your registered mobile number to complete verification.",
        riskScore: 95,
        tactics: ["Authority", "Fear", "Urgency"],
        commentary: "OTP harvesting — the final step. Once shared, the scammer has full account access.",
      },
    ],
    bestBreakPoint: 2,
    breakExplanation: "The malicious URL in Step 3 is the clearest red flag. Banks never send KYC update links via SMS. You should have stopped here and called the bank's official helpline.",
    psychology: [
      { tactic: "Authority", emotion: "Trust", why: "Naming a real bank (SBI) triggers automatic trust in institutional communication.", whyWorks: "People are conditioned to comply with bank instructions without questioning legitimacy." },
      { tactic: "Fear", emotion: "Anxiety", why: "Threatening permanent account closure creates immediate emotional distress.", whyWorks: "Fear of financial loss overrides rational verification instincts." },
      { tactic: "Urgency", emotion: "Panic", why: "The 24-hour deadline prevents the victim from consulting others or verifying.", whyWorks: "Time pressure reduces deliberation and increases impulsive compliance." },
    ],
    prevention: {
      immediate: ["Do not click any links in SMS messages from banks", "Call the bank's official helpline number from their website", "Never share OTP with anyone, including bank representatives"],
      preventive: ["Enable transaction alerts on your bank account", "Bookmark your bank's official website", "Register for the bank's official mobile app for KYC updates"],
      verification: ["Visit the nearest bank branch in person for KYC", "Call the number printed on the back of your debit card", "Check the bank's official website for KYC requirements"],
    },
  },
  {
    id: "otp-phish",
    title: "OTP Phishing",
    short: "OTP Theft",
    icon: "key",
    description: "Extracts one-time passwords by impersonating bank security or delivery services.",
    steps: [
      {
        sender: "scammer",
        message: "This is the Fraud Prevention Department of HDFC Bank. We have detected suspicious activity on your account.",
        riskScore: 25,
        tactics: ["Authority"],
        commentary: "The scammer poses as bank security — a role that inherently demands compliance.",
      },
      {
        sender: "scammer",
        message: "A transaction of ₹49,999 is being processed from your account. Did you authorize this?",
        riskScore: 50,
        tactics: ["Authority", "Fear"],
        commentary: "A fake transaction creates immediate panic. The victim wants to stop the 'fraud'.",
      },
      {
        sender: "victim",
        message: "No! I did not authorize this. Please stop it!",
        riskScore: 50,
        tactics: ["Authority", "Fear"],
        commentary: "The victim is now emotionally engaged and willing to cooperate with the scammer.",
      },
      {
        sender: "scammer",
        message: "To cancel this transaction, I need to verify your identity. Please share the OTP that was just sent to your mobile.",
        riskScore: 85,
        tactics: ["Authority", "Fear", "Urgency"],
        commentary: "The critical moment — requesting OTP under the guise of 'cancelling' the fake transaction.",
      },
      {
        sender: "victim",
        message: "The OTP is 847293. Please cancel the transaction quickly!",
        riskScore: 95,
        tactics: ["Authority", "Fear", "Urgency"],
        commentary: "OTP shared. The scammer now initiates a real transaction using the victim's credentials.",
      },
    ],
    bestBreakPoint: 3,
    breakExplanation: "No bank will ever ask for your OTP over phone or SMS. The moment someone requests your OTP, the interaction is fraudulent — regardless of who they claim to be.",
    psychology: [
      { tactic: "Authority", emotion: "Trust", why: "Claiming to be the 'Fraud Prevention Department' positions the scammer as a protector.", whyWorks: "Victims believe they are being helped, not scammed." },
      { tactic: "Fear", emotion: "Panic", why: "A large unauthorized transaction creates immediate financial anxiety.", whyWorks: "The desire to prevent loss overrides security awareness." },
      { tactic: "Urgency", emotion: "Pressure", why: "Implying the transaction is in progress creates time pressure.", whyWorks: "Victims skip verification steps when they believe delay means loss." },
    ],
    prevention: {
      immediate: ["Never share OTP with anyone — banks will never ask for it", "Hang up and call the number on the back of your card", "Check your bank app for actual transaction history"],
      preventive: ["Set up transaction limits on your account", "Enable app-based transaction approval instead of SMS OTP", "Register your number with the Do Not Disturb registry"],
      verification: ["Call the bank using the number on their official website", "Visit your nearest branch if concerned about account security", "Check your statement through the official banking app"],
    },
  },
  {
    id: "refund-phish",
    title: "Refund Phishing",
    short: "Fake Refund",
    icon: "receipt",
    description: "Claims a refund failed and tricks victims into sharing banking details to 'process' the refund.",
    steps: [
      {
        sender: "scammer",
        message: "Dear Customer, we attempted to process your refund of ₹2,499 but your bank rejected the transaction.",
        riskScore: 20,
        tactics: ["Financial Pressure"],
        commentary: "Establishes a false premise — the victim believes they are owed money.",
      },
      {
        sender: "scammer",
        message: "To receive your refund, please confirm your account details at: http://refund-process-secure.com",
        riskScore: 50,
        tactics: ["Financial Pressure", "Urgency"],
        commentary: "A phishing URL is introduced. The promise of money lowers the victim's guard.",
      },
      {
        sender: "scammer",
        message: "This refund link will expire within 6 hours. Please complete verification to avoid cancellation.",
        riskScore: 70,
        tactics: ["Financial Pressure", "Urgency", "Fear"],
        commentary: "Time pressure is added — the victim fears losing the refund if they don't act quickly.",
      },
      {
        sender: "victim",
        message: "I entered my bank details on the form...",
        riskScore: 90,
        tactics: ["Financial Pressure", "Urgency", "Fear"],
        commentary: "Banking credentials have been submitted to a phishing page. The scammer now has account access.",
      },
    ],
    bestBreakPoint: 1,
    breakExplanation: "Legitimate companies process refunds automatically to the original payment method. They never ask you to 'confirm account details' via a link. Stop at the first request for banking information.",
    psychology: [
      { tactic: "Financial Pressure", emotion: "Greed/Loss", why: "The promise of receiving money creates a positive incentive to engage.", whyWorks: "People are more trusting when they believe they're receiving, not giving." },
      { tactic: "Urgency", emotion: "FOMO", why: "A 6-hour expiry creates fear of missing the refund window.", whyWorks: "Time pressure prevents research and verification." },
      { tactic: "Fear", emotion: "Anxiety", why: "Threatening cancellation of the refund creates loss aversion.", whyWorks: "The desire to not lose money overrides security instincts." },
    ],
    prevention: {
      immediate: ["Never enter bank details on links from messages", "Check your original order/service account for refund status", "Contact the company through their official app or website"],
      preventive: ["Use virtual cards for online purchases", "Monitor bank statements regularly", "Enable transaction notifications"],
      verification: ["Log into the original service to check refund status", "Call the company's official customer service number", "Verify the sender's email domain matches the company"],
    },
  },
  {
    id: "family-impersonation",
    title: "Family Impersonation",
    short: "\"Hi Dad\"",
    icon: "users",
    description: "Impersonates a family member from a 'new number' and requests urgent money transfer.",
    steps: [
      {
        sender: "scammer",
        message: "Hi Dad, I lost my phone. This is my new number.",
        riskScore: 15,
        tactics: ["Emotional Manipulation"],
        commentary: "Establishes emotional connection by impersonating a family member. Seems harmless initially.",
      },
      {
        sender: "scammer",
        message: "My old number stopped working. I had to get a new SIM urgently.",
        riskScore: 30,
        tactics: ["Emotional Manipulation"],
        commentary: "Provides a plausible explanation to prevent the victim from calling the old number to verify.",
      },
      {
        sender: "scammer",
        message: "Dad, I'm in an emergency situation. I urgently need ₹10,000. Can you send it on Google Pay?",
        riskScore: 65,
        tactics: ["Emotional Manipulation", "Urgency", "Financial Pressure"],
        commentary: "The financial request is introduced with urgency and emotional pressure. This is the escalation point.",
      },
      {
        sender: "scammer",
        message: "Please send it now, I'll explain everything later. I'm really stuck.",
        riskScore: 80,
        tactics: ["Emotional Manipulation", "Urgency", "Financial Pressure"],
        commentary: "Prevents questions by promising to explain 'later'. Maintains urgency to prevent verification.",
      },
      {
        sender: "victim",
        message: "Sending now. Are you okay?",
        riskScore: 90,
        tactics: ["Emotional Manipulation", "Urgency", "Financial Pressure"],
        commentary: "Money sent. The scammer will likely request more or disappear. Funds are unrecoverable.",
      },
    ],
    bestBreakPoint: 2,
    breakExplanation: "The moment someone from a 'new number' requests money, verify by calling their OLD number. A real family member will understand verification. The urgency is designed to prevent this check.",
    psychology: [
      { tactic: "Emotional Manipulation", emotion: "Love/Concern", why: "Exploits the parent-child bond — parents instinctively want to help their children.", whyWorks: "Emotional bonds override rational verification. Love bypasses skepticism." },
      { tactic: "Urgency", emotion: "Panic", why: "The word 'emergency' triggers protective instincts and panic.", whyWorks: "Parents act immediately when they believe their child is in danger." },
      { tactic: "Financial Pressure", emotion: "Obligation", why: "Requesting a specific amount makes the demand feel concrete and real.", whyWorks: "The specificity creates legitimacy. The amount feels reasonable enough to not question." },
    ],
    prevention: {
      immediate: ["Call the person's OLD saved number immediately", "Ask a personal question only they would know", "Do not transfer money until identity is verified via video call"],
      preventive: ["Establish a family code word for emergencies", "Discuss this scam type with elderly family members", "Set up UPI transfer limits"],
      verification: ["Video call the person before transferring money", "Contact other family members to confirm the situation", "Wait 30 minutes — urgency is always manufactured"],
    },
  },
  {
    id: "investment-scam",
    title: "Investment / Crypto Scam",
    short: "Fake Investment",
    icon: "trending",
    description: "Promises guaranteed high returns on investments or cryptocurrency, then disappears with the money.",
    steps: [
      {
        sender: "scammer",
        message: "Exclusive investment opportunity: Our AI-powered crypto trading bot guarantees 40% monthly returns. Limited spots available.",
        riskScore: 25,
        tactics: ["Reward", "Scarcity"],
        commentary: "Unrealistic returns are the first red flag. No legitimate investment guarantees 40% monthly returns.",
      },
      {
        sender: "scammer",
        message: "Join our Telegram group to see live profit screenshots from our 10,000+ members who are already earning.",
        riskScore: 40,
        tactics: ["Reward", "Scarcity", "Authority"],
        commentary: "Social proof is manufactured. Screenshots are fabricated. Member count is inflated or fake.",
      },
      {
        sender: "scammer",
        message: "Start with just ₹5,000. Your first withdrawal will be processed within 48 hours to build trust.",
        riskScore: 55,
        tactics: ["Reward", "Scarcity", "Authority"],
        commentary: "Small initial investment and quick withdrawal builds false trust. This is bait for larger deposits.",
      },
      {
        sender: "victim",
        message: "I invested ₹5,000 and received ₹7,000 back! This is real!",
        riskScore: 60,
        tactics: ["Reward"],
        commentary: "The small payout is funded by other victims' deposits (Ponzi structure). It's designed to make you invest more.",
      },
      {
        sender: "scammer",
        message: "Premium tier unlocked! Invest ₹50,000 now for 60% returns. This tier closes in 12 hours.",
        riskScore: 85,
        tactics: ["Reward", "Scarcity", "Urgency"],
        commentary: "The real extraction — after building trust with a small payout, the scammer pushes for a much larger investment.",
      },
      {
        sender: "victim",
        message: "I transferred ₹50,000. When will I see returns?",
        riskScore: 95,
        tactics: ["Reward", "Scarcity", "Urgency"],
        commentary: "The scammer will either disappear or demand more 'fees'. The ₹50,000 is gone.",
      },
    ],
    bestBreakPoint: 0,
    breakExplanation: "No investment guarantees fixed returns. The initial 'profit' you received was bait funded by other victims. Any promise of guaranteed high returns is a scam — always.",
    psychology: [
      { tactic: "Reward", emotion: "Greed", why: "Guaranteed high returns exploit the desire for easy money.", whyWorks: "Greed overrides risk assessment. The promise of wealth suspends critical thinking." },
      { tactic: "Scarcity", emotion: "FOMO", why: "'Limited spots' and 'tier closing' create artificial urgency.", whyWorks: "Fear of missing out on a 'genuine opportunity' prevents research." },
      { tactic: "Authority", emotion: "Trust", why: "Large member counts and profit screenshots create social proof.", whyWorks: "If thousands of people are apparently profiting, it must be legitimate." },
    ],
    prevention: {
      immediate: ["No legitimate investment guarantees fixed returns", "Research the company on SEBI's registered entity list", "Never invest through Telegram or WhatsApp groups"],
      preventive: ["Only invest through SEBI-registered brokers", "Be skeptical of any return above market average", "Never share banking details with investment contacts"],
      verification: ["Check SEBI registration at sebi.gov.in", "Verify the company's physical address and registration", "Consult a certified financial advisor before investing"],
    },
  },
  {
    id: "vendor-payment",
    title: "Corporate Vendor Fraud",
    short: "Invoice Scam",
    icon: "briefcase",
    description: "Targets businesses with fake invoice updates or bank detail change requests from impersonated vendors.",
    steps: [
      {
        sender: "scammer",
        message: "Dear Accounts Team, this is regarding the pending invoice #INV-2024-0847 for ₹3,45,000.",
        riskScore: 15,
        tactics: ["Authority"],
        commentary: "The scammer uses specific invoice formatting to appear legitimate. They may have gathered real vendor names through reconnaissance.",
      },
      {
        sender: "scammer",
        message: "Due to a recent bank migration, our payment details have been updated. Please use the new account for all future payments.",
        riskScore: 45,
        tactics: ["Authority", "Financial Pressure"],
        commentary: "Bank detail change requests are the core of vendor fraud. This single message can redirect lakhs of rupees.",
      },
      {
        sender: "scammer",
        message: "Updated bank details: IFSC: HDFC0001234, A/C: 50100487654321. Please process payment by EOD to avoid supply chain delays.",
        riskScore: 75,
        tactics: ["Authority", "Financial Pressure", "Urgency"],
        commentary: "Urgency is added — 'by EOD' prevents verification through proper channels.",
      },
      {
        sender: "victim",
        message: "Payment of ₹3,45,000 processed to the new account.",
        riskScore: 95,
        tactics: ["Authority", "Financial Pressure", "Urgency"],
        commentary: "Funds sent to a fraudulent account. Recovery is extremely difficult once wire transfers are completed.",
      },
    ],
    bestBreakPoint: 1,
    breakExplanation: "ANY request to change bank details must be verified through a known contact at the vendor — not through the email/message that requested the change. Always call using a previously verified phone number.",
    psychology: [
      { tactic: "Authority", emotion: "Compliance", why: "Using real vendor names and invoice numbers creates legitimacy.", whyWorks: "Finance teams process routine payments without questioning established vendor relationships." },
      { tactic: "Financial Pressure", emotion: "Obligation", why: "Outstanding invoices create a sense of obligation to pay.", whyWorks: "Accounts teams prioritize timely payments to maintain vendor relationships." },
      { tactic: "Urgency", emotion: "Pressure", why: "'EOD' deadlines prevent proper verification workflows.", whyWorks: "Time pressure causes shortcuts in approval processes." },
    ],
    prevention: {
      immediate: ["Never process bank detail changes from email/SMS alone", "Call the vendor on their known phone number to verify", "Implement dual-authorization for payment detail changes"],
      preventive: ["Establish a formal vendor bank detail change process", "Train finance teams on vendor impersonation tactics", "Use vendor management portals for payment information"],
      verification: ["Call the vendor using a number from your existing records", "Request written confirmation on official vendor letterhead", "Verify through multiple contacts at the vendor organization"],
    },
  },
  {
    id: "police-threat",
    title: "Government / Police Threat",
    short: "Police Scam",
    icon: "shield",
    description: "Impersonates police or government officials, threatening arrest unless immediate payment is made.",
    steps: [
      {
        sender: "scammer",
        message: "This is an automated message from the Cyber Crime Division. Your Aadhaar number has been linked to illegal activities. Press 1 to connect with the investigating officer.",
        riskScore: 30,
        tactics: ["Authority", "Fear"],
        commentary: "IVR-style scam. Government agencies never contact citizens through automated threatening calls.",
      },
      {
        sender: "scammer",
        message: "I am Inspector Sharma from Delhi Cyber Cell. Your Aadhaar has been used for money laundering. FIR #CBI-2024-4829 has been registered against you.",
        riskScore: 55,
        tactics: ["Authority", "Fear"],
        commentary: "Using official-sounding names, designations, and fake FIR numbers creates false credibility.",
      },
      {
        sender: "scammer",
        message: "You must appear before the magistrate within 2 hours or an arrest warrant will be issued. To avoid arrest, you must cooperate now.",
        riskScore: 75,
        tactics: ["Authority", "Fear", "Urgency"],
        commentary: "The threat of arrest is designed to create panic. Real legal proceedings don't work this way.",
      },
      {
        sender: "scammer",
        message: "Transfer ₹1,50,000 to this verification account as security deposit. It will be refunded after investigation: UPI - cybercell.verify@ybl",
        riskScore: 90,
        tactics: ["Authority", "Fear", "Urgency", "Financial Pressure"],
        commentary: "The financial demand reveals the scam. No government agency accepts payments via UPI to personal accounts.",
      },
      {
        sender: "victim",
        message: "I transferred the money. When will this be resolved?",
        riskScore: 95,
        tactics: ["Authority", "Fear", "Urgency", "Financial Pressure"],
        commentary: "The scammer will demand more 'fees' or disappear. Government agencies never request money via UPI.",
      },
    ],
    bestBreakPoint: 0,
    breakExplanation: "Government agencies and police NEVER threaten arrest via phone calls or ask for money via UPI. This is always a scam. Hang up immediately and report to the real cyber crime helpline (1930).",
    psychology: [
      { tactic: "Authority", emotion: "Compliance", why: "Police and government carry maximum authority in Indian society.", whyWorks: "Citizens are conditioned to obey authority figures without question." },
      { tactic: "Fear", emotion: "Terror", why: "Arrest threats trigger primal fear — loss of freedom, social shame.", whyWorks: "The fear of imprisonment overrides all rational analysis." },
      { tactic: "Urgency", emotion: "Panic", why: "'Within 2 hours' prevents the victim from consulting a lawyer or family.", whyWorks: "Isolation from advisors is critical for the scam to succeed." },
    ],
    prevention: {
      immediate: ["Hang up immediately — this is always a scam", "Call the real Cyber Crime helpline: 1930", "No government agency requests money via UPI or phone"],
      preventive: ["Inform elderly family members about this specific scam", "Save the actual cyber crime helpline number (1930)", "Know that FIRs cannot be 'resolved' with money"],
      verification: ["Visit the nearest police station in person if concerned", "Call 100 (police) or 1930 (cyber crime) to verify", "Consult a lawyer before taking any action on threats"],
    },
  },
];

export default SIMULATIONS;